# Generated by Django 4.2.3 on 2023-07-31 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(default='This is the Sub Heading.', max_length=200),
        ),
    ]
